services:
  - type: web
    name: triplea-travel-bot
    env: python
    plan: standard   # можно оставить starter, если нагрузка небольшая
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bot:app --host 0.0.0.0 --port $PORT
    autoDeploy: false   # отключает авто-деплой при каждом пуше
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEBHOOK_URL
        value: https://tour-bot-rxi8.onrender.com
