services:
  - type: web
    name: tour-bot
    env: python
    plan: standard   # можно оставить starter, если нагрузка небольшая
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bot:app --host 0.0.0.0 --port $PORT
    autoDeploy: false
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEBHOOK_HOST
        value: https://tour-bot-rxi8.onrender.com
      - key: WEBHOOK_PATH
        value: /webhook
        
        # ===== PAYMENTS (Click) =====
      - key: CLICK_MERCHANT_ID
        sync: false
      - key: CLICK_SERVICE_ID
        sync: false
      - key: CLICK_SECRET_KEY
        sync: false
      - key: CLICK_BASE_CHECKOUT
        value: https://my.click.uz/services/pay
      - key: CLICK_RETURN_URL
        value: https://tour-bot-rxi8.onrender.com/pay/success
      - key: CLICK_CANCEL_URL
        value: https://tour-bot-rxi8.onrender.com/pay/cancel

      # ===== PAYMENTS (Payme/Paycom) =====
      - key: PAYME_MERCHANT_ID
        sync: false
      - key: PAYME_SECRET_KEY
        sync: false
      - key: PAYME_BASE_CHECKOUT
        value: https://checkout.paycom.uz
      - key: PAYME_RETURN_URL
        value: https://tour-bot-rxi8.onrender.com/pay/success
      - key: PAYME_CANCEL_URL
        value: https://tour-bot-rxi8.onrender.com/pay/cancel

  - type: worker
    name: Collector
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python collector.py
    autoDeploy: false
    envVars:
      - key: TG_API_ID
        sync: false
      - key: TG_API_HASH
        sync: false
      - key: TG_SESSION_B64
        sync: false
      - key: CHANNELS
        value: "@tour1,@tour2,@tour3"
      - key: DATABASE_URL
        sync: false

    envVars:
  - key: TELEGRAM_TOKEN
    sync: false
  - key: OPENAI_API_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: WEBHOOK_HOST
    value: https://tour-bot-rxi8.onrender.com
  - key: WEBHOOK_PATH
    value: /webhook
  - key: LEADS_CHAT_ID
    value: "-4806023117"   # твой ID группы заявок
  - key: LEADS_TOPIC_ID
    value: ""              # если не используешь Темы, оставь пустым
  - key: ADMIN_USER_ID
    value: "557891018"     # твой user_id для админ-команд

    services:
  - type: web
    name: tour-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install -r requirements-dev.txt
    startCommand: uvicorn bot:app --host 0.0.0.0 --port $PORT
    # опционально: если тесты есть и они быстрые
    preDeployCommand: pytest -m "not integration" -q




