services:
  - type: web
    name: triplea-travel-bot
    env: python
    plan: standard   # можно оставить starter, если нагрузка небольшая
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: false   # чтобы не падало при каждом пуше
    healthCheckPath: /healthz
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEBHOOK_URL
        value: https://tour-bot-rxi8.onrender.com/webhook
