name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]   # держим паритет с продом
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint (black/isort/flake8)
        run: |
          black --check .
          isort --check-only .
          flake8 .
      - name: Type check (mypy)
        run: mypy .
      - name: Security (bandit)
        run: bandit -r .
      - name: Tests
        run: pytest
